-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguVYG7ftzKnvf6eqG
xf+zP8qhKfIKNQthsvCt0MedmXCgCgYIKoZIzj0DAQehRANCAASJFyqQYyajtcix
7rIFBmvWjJWqJGIp6MVuJL34SF9LJg2v1y1/DutAZfnvajHqt9lpN7A0C+TTySOh
f4HQX07E
-----END PRIVATE KEY-----